name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zlib1g-dev openjdk-8-jdk unzip ccache libncurses5 wget

    - name: Setup Android SDK
      run: |
        mkdir -p ~/android-sdk
        cd ~/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        rm commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv tools/* cmdline-tools/latest/
        yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "build-tools;30.0.3" "platform-tools" "platforms;android-28" "ndk;21.4.7075529"
        mv ~/android-sdk ~/.buildozer/android/platform/android-sdk

    - name: Install Buildozer
      run: pip install buildozer==1.4.0 cython==0.29.21

    - name: Build APK
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3, kivy==2.0.0, telethon
        android.permissions = INTERNET
        android.api = 28
        android.minapi = 21
        android.skip_update = True
        " > buildozer.spec
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
