name: Build HaydeChecker APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-17-jdk \
          unzip \
          ccache

    - name: Install Buildozer
      run: pip install buildozer

    - name: Configure buildozer.spec
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3==3.9.0,kivy==2.0.0,telethon==1.24.0,pycryptodome
        android.permissions = INTERNET, READ_EXTERNAL_STORAGE
        android.api = 31
        android.minapi = 21
        android.ndk_version = 23b
        android.arch = arm64-v8a
        p4a.branch = 2023.08.25" > buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android clean
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
        retention-days: 7
