name: Build HaydeChecker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Используем проверенную LTS-версию
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Fix Ubuntu repositories
      run: |
        sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/g' /etc/apt/sources.list
        sudo apt-get update

    - name: Install exact dependencies
      run: |
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-8-jdk \
          unzip \
          ccache \
          libncurses5 \
          build-essential \
          python3-dev \
          git

    - name: Install Buildozer with locked versions
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.2.0
        pip install cython==0.29.21
        pip install virtualenv

    - name: Configure minimal buildozer.spec
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3==3.8.10, kivy==2.0.0, telethon==1.24.0
        android.permissions = INTERNET
        android.api = 28
        android.minapi = 21
        android.ndk_version = 21d  # Автоматически скачается
        android.arch = arm64-v8a
        " > buildozer.spec

    - name: Build with retries
      run: |
        for i in {1..3}; do
          buildozer -v android clean && break || sleep 10
        done
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
        retention-days: 3
