name: Build HaydeChecker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-8-jdk \
          unzip \
          ccache \
          libncurses5 \
          wget \
          ca-certificates

    - name: Setup Android SDK (Fixed)
      run: |
        # Создаем всю структуру директорий заранее
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        cd ~/.buildozer/android/platform
        
        # Скачиваем и распаковываем tools прямо в целевую директорию
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip -q commandlinetools-linux-8512546_latest.zip -d tmp_tools
        mv tmp_tools/cmdline-tools/* ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
        rm -rf tmp_tools commandlinetools-linux-8512546_latest.zip
        
        # Устанавливаем компоненты
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
          "build-tools;30.0.3" \
          "platform-tools" \
          "platforms;android-28" \
          "ndk;21.4.7075529"

    - name: Verify Android tools
      run: |
        ls -la ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --list_installed

    - name: Install Buildozer
      run: |
        pip install buildozer==1.4.0
        pip install cython==0.29.21

    - name: Configure buildozer.spec
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3, kivy==2.0.0, telethon
        android.permissions = INTERNET
        android.api = 28
        android.minapi = 21
        android.sdk_path = $HOME/.buildozer/android/platform/android-sdk
        android.ndk_path = $HOME/.buildozer/android/platform/android-sdk/ndk/21.4.7075529
        android.skip_update = True
        " > buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android clean || true
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
        retention-days: 7
