name: Build HaydeChecker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Используем более старую версию Ubuntu
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9  # Понижаем версию Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-11-jdk \  # Используем JDK 11 вместо 17
          unzip \
          ccache \
          libncurses5  # Для Ubuntu 22.04

    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer==1.4.0  # Стабильная версия
        pip install cython==0.29.33
        pip install python-for-android==0.11.0  # Проверенная версия

    - name: Configure buildozer.spec
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3==3.9.0,kivy==2.1.0,telethon,pycryptodome
        android.permissions = INTERNET, READ_EXTERNAL_STORAGE
        android.api = 30  # Более старая версия API
        android.minapi = 21
        android.ndk_version = 23b  # Проверенная версия NDK
        android.archs = arm64-v8a
        android.debug = False" > buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android clean || true
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
        retention-days: 7
