name: Build HaydeChecker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Гарантированно рабочая версия
    timeout-minutes: 50

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8  # Самая стабильная версия
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-8-jdk \  # JDK 8 - самый стабильный вариант
          unzip \
          ccache \
          libncurses5

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.3.0  # Проверенная версия
        pip install cython==0.29.21

    - name: Configure buildozer.spec
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3,kivy==2.0.0,telethon==1.24.0
        android.permissions = INTERNET
        android.api = 28  # Android 9 (Pie)
        android.minapi = 21
        android.ndk_version = 21.3.6528147  # Автоматическая версия
        android.arch = arm64-v8a  # Только 64-bit
        " > buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android clean 2>&1 | tee clean.log
        buildozer -v android debug 2>&1 | tee build.log

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
        retention-days: 3
