name: Build HaydeChecker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            zlib1g-dev \
            python3-dev \
            openjdk-17-jdk \
            unzip \
            ccache \
            libncurses5

      - name: Install Buildozer
        run: pip install buildozer

      - name: Configure Buildozer
        run: |
          cat << EOF > buildozer.spec
          [app]
          title = HaydeChecker
          package.name = haydechecker
          package.domain = org.hayde
          source.dir = .
          version = 1.0
          requirements = python3==3.9.0, kivy==2.3.0, telethon==1.28.0, pycryptodome==3.18.0, pysocks==1.7.1
          android.permissions = INTERNET, READ_EXTERNAL_STORAGE
          android.api = 34
          android.ndk_version = 23b
          android.arch = arm64-v8a
          p4a.branch = develop
          EOF

      - name: Build APK (Debug)
        run: |
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HaydeChecker-Debug
          path: bin/*debug.apk
          retention-days: 7
