name: Build HaydeChecker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90  # Увеличиваем время ожидания

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-8-jdk \
          unzip \
          ccache \
          libncurses5 \
          wget \
          ca-certificates

    - name: Pre-download NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget -q --show-progress --progress=bar:force https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip -q android-ndk-r21e-linux-x86_64.zip
        rm android-ndk-r21e-linux-x86_64.zip
        mv android-ndk-r21e android-ndk

    - name: Install Buildozer
      run: |
        pip install buildozer==1.4.0
        pip install cython==0.29.21

    - name: Configure buildozer.spec
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3, kivy==2.0.0, telethon
        android.permissions = INTERNET
        android.api = 28
        android.minapi = 21
        android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk
        android.ndk_version = 21.1.6352462
        android.skip_update = True
        " > buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android clean || true
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
        retention-days: 7
