name: Build HaydeChecker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-8-jdk \
          unzip \
          ccache \
          libncurses5 \
          wget \
          git

    - name: Pre-install Android SDK and NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # Установка Android SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        rm -rf cmdline-tools commandlinetools-linux-9477386_latest.zip
        
        # Установка NDK
        wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip -q android-ndk-r21e-linux-x86_64.zip
        rm android-ndk-r21e-linux-x86_64.zip

    - name: Install python-for-android manually
      run: |
        mkdir -p ~/.buildozer/android/platform/python-for-android
        git clone -b 2023.08.25 --depth 1 https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android
        cd ~/.buildozer/android/platform/python-for-android
        python -m pip install -e .

    - name: Install Buildozer
      run: |
        python -m pip install buildozer==1.5.0
        python -m pip install cython==0.29.33

    - name: Configure buildozer.spec
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3, kivy==2.0.0, telethon
        android.permissions = INTERNET
        android.api = 28
        android.minapi = 21
        android.sdk_path = /home/runner/.buildozer/android/platform/android-sdk
        android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r21e
        p4a.branch = 2023.08.25
        " > buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android clean || true
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
        retention-days: 7
