name: Build HaydeChecker APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev \
          openjdk-17-jdk \
          unzip \
          ccache \
          libncurses6 \
          git \
          make \
          autoconf \
          automake \
          libtool

    - name: Install Buildozer with explicit p4a
      run: |
        pip install buildozer==1.5.0
        pip install cython==0.29.36
        pip install python-for-android==2024.1.21

    - name: Pre-initialize p4a
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        git clone --depth 1 --branch 2024.1.21 https://github.com/kivy/python-for-android.git
        cd python-for-android
        python -m pip install -e .

    - name: Configure buildozer.spec
      run: |
        echo "[app]
        title = HaydeChecker
        package.name = haydechecker
        package.domain = org.hayde
        source.dir = .
        version = 1.0
        requirements = python3==3.9.0,kivy==2.2.1,telethon==1.34.0,pycryptodome==3.20.0
        android.permissions = INTERNET, READ_EXTERNAL_STORAGE
        android.api = 34
        android.minapi = 21
        android.ndk_version = 25
        android.archs = arm64-v8a
        p4a.branch = 2024.1.21
        android.strip = True
        android.debug = False" > buildozer.spec

    - name: Build APK (with retry)
      run: |
        buildozer -v android clean || true
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HaydeChecker-APK
        path: bin/*.apk
        retention-days: 7
